projects:
  myshipments:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: ise34g5mjvcmlddrmictyra4d4
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-west-2
      endpoints:
        prod: >-
          https://au7x2hprqvbf7l3xiekyxzscji.appsync-api.us-west-2.amazonaws.com/graphql
