// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://au7x2hprqvbf7l3xiekyxzscji.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cwn4pg5rxvevpmgktvwaxk3tei",
    "aws_cognito_identity_pool_id": "us-west-2:ff0ad325-8115-48f5-838c-717bc9ef4a2b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_6UAmUM3mY",
    "aws_user_pools_web_client_id": "3eui2s60fg3bjf6t376lqae1gv",
    "aws_mobile_analytics_app_id": "a2c23fba80914e358d11f514f29856c9",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
